// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDork(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddDork'](arg1, arg2, arg3);
}

export function AllCategories(arg1) {
  return window['go']['main']['App']['AllCategories'](arg1);
}

export function AllDorks() {
  return window['go']['main']['App']['AllDorks']();
}

export function DeleteDork(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteDork'](arg1, arg2, arg3);
}

export function Dorker(arg1, arg2) {
  return window['go']['main']['App']['Dorker'](arg1, arg2);
}
