// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddDork(arg1:string,arg2:string,arg3:string):Promise<string>;

export function AllCategories(arg1:string):Promise<Array<string>>;

export function AllDorks():Promise<Record<string, Record<string, Array<string>>>>;

export function DeleteDork(arg1:string,arg2:string,arg3:string):Promise<string>;

export function Dorker(arg1:string,arg2:string):Promise<Array<main.Result>>;
